version: '3.8'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: 192.168.165.28:8083/python/doc-agent:latest
    container_name: doc-agent-app
    restart: unless-stopped
    ports:
      - "53518:53518"
    volumes:
      - ./:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge